window.NAI_SUPPORTED_GPUS = [
  { id: 'l40s_48g', label: 'NVIDIA L40S-48G', shortLabel: 'L40S-48G', vramGb: 48, sourcePage: 15 },
  { id: 'a100_80g', label: 'NVIDIA A100-80G', shortLabel: 'A100-80G', vramGb: 80, sourcePage: 15 },
  { id: 'h100_80g', label: 'NVIDIA H100-80G', shortLabel: 'H100-80G', vramGb: 80, sourcePage: 15 },
  { id: 'h100_nvl_94g', label: 'NVIDIA H100 NVL-94G', shortLabel: 'H100 NVL-94G', vramGb: 94, sourcePage: 15 },
  { id: 'h200_141g', label: 'NVIDIA H200-141G', shortLabel: 'H200-141G', vramGb: 141, sourcePage: 15 },
  { id: 'rtx_pro_6000_96g', label: 'NVIDIA RTX PRO 6000-96G', shortLabel: 'RTX PRO 6000-96G', vramGb: 96, sourcePage: 15 }
];

window.NAI_PLATFORM_BASELINE = {
  source: 'Nutanix-Enterprise-AI-v2_6.pdf',
  sourcePages: [16, 17, 18],
  controlPlane: { nodes: 3, vcpuPerNode: 4, memoryPerNodeGb: 16, storagePerNodeGb: 150 },
  worker: { nodes: 3, vcpuPerNode: 8, memoryPerNodeGb: 16, storagePerNodeGb: 150 },
  storage: {
    rwoBlockGiB: 55,
    rwxNfsTiB: 2,
    s3CompatibleTiB: 1
  },
  validatedCapacityNote: 'Validated baseline supports 50 inference endpoints, 150 API keys per endpoint, and 5 concurrent MLAdmin users. Dedicated GPU node pool required.'
};

window.NAI_COMPONENT_OVERHEAD = [
  { label: 'NAI API', cpu: '8 vCPU', memory: '4 GiB', purpose: 'API endpoint' },
  { label: 'NAI DB', cpu: '4 vCPU', memory: '4 GiB', purpose: 'Application data' },
  { label: 'ClickHouse Server', cpu: '4 vCPU', memory: '8 GiB', purpose: 'Observability data store' },
  { label: 'NAI UI', cpu: '2 vCPU', memory: '2 GiB', purpose: 'Frontend UI' },
  { label: 'Model Controller', cpu: '500m', memory: '0.49 GiB', purpose: 'LLM model controller' },
  { label: 'Gateway Control Plane', cpu: '300m', memory: '1 GiB', purpose: 'Envoy Gateway control plane' },
  { label: 'Gateway Data Plane', cpu: '1 vCPU', memory: '4 GiB', purpose: 'Ingress data plane proxy' }
];

window.NAI_VALIDATED_MODEL_CATALOG = [
  {
    id: 'hf-meta-llama-3.1-8b-instruct',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'Meta-Llama-3.1-8B-Instruct',
    modalities: ['text'],
    taskTags: ['chat', 'rag', 'assistant'],
    planningClass: 'small-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['internal-chatbot', 'customer-support-rag', 'knowledge-search', 'hr-policy-bot', 'it-helpdesk', 'onboarding-assistant', 'branch-assistant'],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'hf-meta-llama-3.1-70b-instruct',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'Meta-Llama-3.1-70B-Instruct',
    modalities: ['text'],
    taskTags: ['reasoning', 'agentic', 'rag'],
    planningClass: 'large-text',
    supportedGpuCounts: { l40s_48g: 4, a100_80g: 2, h100_80g: 2, h100_nvl_94g: 2, h200_141g: 2, rtx_pro_6000_96g: 2 },
    defaultUseCases: ['executive-copilot', 'security-triage', 'legal-discovery', 'operations-war-room'],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'hf-meta-llama-3.3-70b-instruct',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'Meta-Llama-3.3-70B-Instruct',
    modalities: ['text'],
    taskTags: ['reasoning', 'agentic', 'premium'],
    planningClass: 'large-text',
    supportedGpuCounts: { l40s_48g: 4, a100_80g: 2, h100_80g: 2, h100_nvl_94g: 2, h200_141g: 2, rtx_pro_6000_96g: 2 },
    defaultUseCases: ['fraud-investigation', 'graph-rag-investigation', 'agentic-orchestration'],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-codellama-7b-instruct',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'CodeLlama-7B-Instruct-hf',
    modalities: ['text', 'code'],
    taskTags: ['code', 'assistant'],
    planningClass: 'small-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'hf-codellama-34b-instruct',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'CodeLlama-34B-Instruct-hf',
    modalities: ['text', 'code'],
    taskTags: ['code', 'assistant'],
    planningClass: 'medium-text',
    supportedGpuCounts: { l40s_48g: 2, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'hf-meta-llama-3.2-11b-vision-instruct',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Llama-3.2-11B-Vision-Instruct',
    modalities: ['vision', 'text'],
    taskTags: ['vision', 'document-ai', 'multimodal'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['invoice-processing', 'claims-processing', 'image-captioning', 'edge-ocr', 'multimodal-search'],
    sourceTable: 'Table 8',
    sourcePages: [19, 20]
  },
  {
    id: 'hf-meta-llama-3.2-90b-vision-instruct',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Llama-3.2-90B-Vision-Instruct',
    modalities: ['vision', 'text'],
    taskTags: ['vision', 'document-ai', 'premium'],
    planningClass: 'large-text',
    supportedGpuCounts: { l40s_48g: 4, a100_80g: 4, h100_80g: 4, h100_nvl_94g: 4, h200_141g: 2, rtx_pro_6000_96g: 2 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-meta-llama-4-scout-17b-16e',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Llama-4-Scout-17B-16E',
    modalities: ['text', 'multimodal'],
    taskTags: ['reasoning', 'moe', 'premium'],
    planningClass: 'medium-text',
    supportedGpuCounts: { h100_80g: 4, h100_nvl_94g: 4, h200_141g: 2, rtx_pro_6000_96g: 4 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-meta-llama-guard-3-8b',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'Llama-Guard-3-8B',
    modalities: ['text', 'guardrail'],
    taskTags: ['guardrail', 'safety'],
    planningClass: 'guardrail',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['compliance-monitor', 'security-triage'],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-mistral-7b-instruct-v0.3',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'Mistral-7B-Instruct-v0.3',
    modalities: ['text'],
    taskTags: ['chat', 'assistant', 'generation'],
    planningClass: 'small-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['marketing-content', 'translation-service', 'etl-enrichment'],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-mixtral-8x7b-instruct-v0.1',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Mixtral-8x7B-Instruct-v0.1',
    modalities: ['text'],
    taskTags: ['reasoning', 'moe'],
    planningClass: 'medium-text',
    supportedGpuCounts: { l40s_48g: 4, a100_80g: 2, h100_80g: 2, h100_nvl_94g: 2, h200_141g: 1, rtx_pro_6000_96g: 2 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-mixtral-8x22b-instruct-v0.1',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Mixtral-8x22B-Instruct-v0.1',
    modalities: ['text'],
    taskTags: ['reasoning', 'moe'],
    planningClass: 'large-text',
    supportedGpuCounts: { a100_80g: 4, h100_80g: 4, h100_nvl_94g: 4, h200_141g: 4, rtx_pro_6000_96g: 4 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-mistral-nemo-instruct-2407',
    provider: 'hf',
    runtime: 'tgi',
    modelName: 'Mistral-Nemo-Instruct-2407',
    modalities: ['text'],
    taskTags: ['chat', 'assistant', 'rag'],
    planningClass: 'small-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['sales-account-research', 'research-assistant', 'education-tutor', 'proposal-generator', 'procurement-bot'],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-magistral-small-2506',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Magistral-Small-2506',
    modalities: ['text'],
    taskTags: ['reasoning', 'assistant'],
    planningClass: 'medium-text',
    supportedGpuCounts: { a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-devstral-small-2507',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Devstral-Small-2507',
    modalities: ['text', 'code'],
    taskTags: ['code', 'sql', 'reasoning'],
    planningClass: 'medium-text',
    supportedGpuCounts: { a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['code-assistant', 'sql-analyst'],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-ministral-3-14b-instruct-2512',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Ministral-3-14B-Instruct-2512',
    modalities: ['text'],
    taskTags: ['assistant', 'reasoning'],
    planningClass: 'medium-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 4 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'hf-ministral-3-14b-reasoning-2512',
    provider: 'hf',
    runtime: 'vllm',
    modelName: 'Ministral-3-14B-Reasoning-2512',
    modalities: ['text'],
    taskTags: ['reasoning'],
    planningClass: 'medium-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [20]
  },
  {
    id: 'other-google-vit-base-patch16-224',
    provider: 'other-validated',
    runtime: 'vllm',
    modelName: 'google/vit-base-patch16-224',
    modalities: ['vision'],
    taskTags: ['classification', 'vision'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: ['document-classification'],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'other-google-gemma-2-9b-it',
    provider: 'other-validated',
    runtime: 'tgi',
    modelName: 'gemma-2-9b-it',
    modalities: ['text'],
    taskTags: ['assistant', 'chat'],
    planningClass: 'small-text',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'other-ai2-olmo-3-32b-think',
    provider: 'other-validated',
    runtime: 'vllm',
    modelName: 'Olmo-3-32B-Think',
    modalities: ['text'],
    taskTags: ['reasoning'],
    planningClass: 'medium-text',
    supportedGpuCounts: { l40s_48g: 2, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1, rtx_pro_6000_96g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [19]
  },
  {
    id: 'nvidia-llama-3.2-nv-embedqa-1b-v2',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'llama-3.2-nv-embedqa-1b-v2',
    modalities: ['embedding', 'retrieval'],
    taskTags: ['retrieval', 'embedding'],
    planningClass: 'retrieval',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['internal-chatbot', 'knowledge-search', 'multimodal-search'],
    sourceTable: 'Table 8',
    sourcePages: [21]
  },
  {
    id: 'nvidia-llama-3.2-nv-rerankqa-1b-v2',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'llama-3.2-nv-rerankqa-1b-v2',
    modalities: ['reranker', 'retrieval'],
    taskTags: ['retrieval', 'reranking'],
    planningClass: 'retrieval',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['internal-chatbot', 'knowledge-search', 'multimodal-search'],
    sourceTable: 'Table 8',
    sourcePages: [21]
  },
  {
    id: 'nvidia-llama-3.1-nemoguard-8b-content-safety',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'llama-3.1-nemoguard-8b-content-safety',
    modalities: ['text', 'guardrail'],
    taskTags: ['guardrail', 'content-safety'],
    planningClass: 'guardrail',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['security-triage', 'phishing-analysis'],
    sourceTable: 'Table 8',
    sourcePages: [20, 21]
  },
  {
    id: 'nvidia-llama-3.1-nemoguard-8b-topic-control',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'llama-3.1-nemoguard-8b-topic-control',
    modalities: ['text', 'guardrail'],
    taskTags: ['guardrail', 'topic-control'],
    planningClass: 'guardrail',
    supportedGpuCounts: { l40s_48g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['compliance-monitor'],
    sourceTable: 'Table 8',
    sourcePages: [21]
  },
  {
    id: 'nvidia-llama-3.3-70b-instruct',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'llama-3.3-70b-instruct',
    modalities: ['text'],
    taskTags: ['reasoning', 'assistant'],
    planningClass: 'large-text',
    supportedGpuCounts: { l40s_48g: 4, h100_80g: 4, h100_nvl_94g: 4, h200_141g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [21]
  },
  {
    id: 'nvidia-gpt-oss-20b',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'gpt-oss-20b',
    modalities: ['text'],
    taskTags: ['reasoning', 'assistant'],
    planningClass: 'medium-text',
    supportedGpuCounts: { h100_80g: 1, h100_nvl_94g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [22]
  },
  {
    id: 'nvidia-gpt-oss-120b',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'gpt-oss-120b',
    modalities: ['text'],
    taskTags: ['reasoning', 'assistant'],
    planningClass: 'large-text',
    supportedGpuCounts: { h100_80g: 2, h100_nvl_94g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [22]
  },
  {
    id: 'nvidia-nemoretriever-parse',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'nemoretriever-parse',
    modalities: ['document-ai', 'retrieval'],
    taskTags: ['document-ai', 'parse'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { l40s_48g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['contract-review', 'loan-origination', 'legal-discovery'],
    sourceTable: 'Table 8',
    sourcePages: [22]
  },
  {
    id: 'nvidia-nemoretriever-ocr-v1',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'nemoretriever-ocr-v1',
    modalities: ['document-ai', 'ocr'],
    taskTags: ['document-ai', 'ocr'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { l40s_48g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['invoice-processing', 'edge-ocr', 'claims-processing'],
    sourceTable: 'Table 8',
    sourcePages: [22]
  },
  {
    id: 'nvidia-nemoretriever-table-structure-v1',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'nemoretriever-table-structure-v1',
    modalities: ['document-ai', 'ocr'],
    taskTags: ['document-ai', 'table-structure'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { l40s_48g: 1, h100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['invoice-processing', 'claims-processing'],
    sourceTable: 'Table 8',
    sourcePages: [22]
  },
  {
    id: 'nvidia-nemoretriever-graphic-elements-v1',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'nemoretriever-graphic-elements-v1',
    modalities: ['document-ai', 'vision'],
    taskTags: ['document-ai', 'graphics'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { l40s_48g: 1, a100_80g: 1, h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: ['multimodal-search'],
    sourceTable: 'Table 8',
    sourcePages: [22]
  },
  {
    id: 'nvidia-flux-1-dev',
    provider: 'nvidia',
    runtime: 'nvidia-runtime',
    modelName: 'black-forest-labs/flux.1-dev',
    modalities: ['image-generation'],
    taskTags: ['creative', 'image-generation'],
    planningClass: 'vision-doc',
    supportedGpuCounts: { h100_nvl_94g: 1, h200_141g: 1 },
    defaultUseCases: [],
    sourceTable: 'Table 8',
    sourcePages: [21]
  }
];
