window.AI_USE_CASES = [
  {
    id: 'internal-chatbot',
    name: 'Internal knowledge chatbot',
    category: 'Assistant',
    complexity: 'medium',
    pattern: 'Validated RAG',
    desc: 'Employee-facing assistant over enterprise documents and policies.',
    defaults: { users: 200, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + embedqa + rerankqa + vector store' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'reranking'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'customer-support-rag',
    name: 'Customer support document Q&A',
    category: 'RAG',
    complexity: 'medium',
    pattern: 'Validated RAG',
    desc: 'Assist agents or customers with answers from manuals and knowledge-base articles.',
    defaults: { users: 500, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + embedqa + rerankqa + optional parse/OCR companions' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'reranking', 'document-ai'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2', 'nvidia-nemoretriever-parse']
  },
  {
    id: 'executive-copilot',
    name: 'Executive copilot',
    category: 'Assistant',
    complexity: 'high',
    pattern: 'Validated Agentic RAG',
    desc: 'Calendar, mail, documents, and workflow copilot constrained to validated NAI text endpoints.',
    defaults: { users: 50, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-70B-Instruct', 'Llama-3.3-70B-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium validated text endpoint + retrieval + guardrails' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'guardrail'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-70b-instruct', 'hf-meta-llama-3.3-70b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2', 'nvidia-llama-3.1-nemoguard-8b-content-safety']
  },
  {
    id: 'sales-account-research',
    name: 'Sales account research assistant',
    category: 'Assistant',
    complexity: 'medium',
    pattern: 'Validated RAG',
    desc: 'Summarizes account context, opportunities, installed base, and risk using validated text endpoints.',
    defaults: { users: 300, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'meeting-summarization',
    name: 'Meeting summarization',
    category: 'Media',
    complexity: 'medium',
    pattern: 'Unsupported Speech',
    desc: 'Streaming speech transcription and summarization are hidden in strict v2.6 mode because the PDF does not give a clean ASR-backed validated path.',
    defaults: { users: 100, concurrency: 0, latency: 'near-real-time', deployment: 'hybrid' },
    models: ['Not supported in strict NAI v2.6'],
    infra: { gpuMemoryGb: 0, gpuClass: 'Hidden in strict mode', architecture: 'Custom validation required outside the strict catalog' },
    strictVisible: false,
    pdfSupportStatus: 'hidden',
    requiredCapabilities: ['speech'],
    allowedValidatedModelIds: [],
    defaultValidatedModelId: ''
  },
  {
    id: 'call-center-live-assist',
    name: 'Call center live assist',
    category: 'Assistant',
    complexity: 'high',
    pattern: 'Unsupported Speech',
    desc: 'Real-time streaming ASR and assist are hidden in strict v2.6 mode because the PDF does not validate this workload as a complete packaged path.',
    defaults: { users: 1000, concurrency: 0, latency: 'near-real-time', deployment: 'edge + central' },
    models: ['Not supported in strict NAI v2.6'],
    infra: { gpuMemoryGb: 0, gpuClass: 'Hidden in strict mode', architecture: 'Custom validation required outside the strict catalog' },
    strictVisible: false,
    pdfSupportStatus: 'hidden',
    requiredCapabilities: ['speech', 'streaming'],
    allowedValidatedModelIds: [],
    defaultValidatedModelId: ''
  },
  {
    id: 'contract-review',
    name: 'Contract review assistant',
    category: 'Documents',
    complexity: 'medium',
    pattern: 'Validated Document RAG',
    desc: 'Review agreements with validated document parsing, retrieval, and text or vision endpoints.',
    defaults: { users: 120, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Llama-3.2-11B-Vision-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Text or vision endpoint + parse/OCR + embedqa + rerankqa' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-meta-llama-3.2-11b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-parse', 'nvidia-nemoretriever-ocr-v1', 'nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'invoice-processing',
    name: 'Invoice processing',
    category: 'Vision',
    complexity: 'medium',
    pattern: 'Validated Document AI',
    desc: 'Extract fields from invoices using validated vision and document retriever endpoints.',
    defaults: { users: 50, concurrency: 0, latency: 'near-real-time', deployment: 'edge' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Llama-3.2-90B-Vision-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or H200-141G', architecture: 'Vision endpoint + OCR + parse + table-structure companions' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'vision', 'ocr'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.2-90b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-ocr-v1', 'nvidia-nemoretriever-parse', 'nvidia-nemoretriever-table-structure-v1']
  },
  {
    id: 'claims-processing',
    name: 'Insurance claims intake',
    category: 'Vision',
    complexity: 'high',
    pattern: 'Validated Multimodal Intake',
    desc: 'Process claim forms, photos, and notes with validated vision endpoints and document retriever services.',
    defaults: { users: 200, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Llama-3.2-90B-Vision-Instruct'],
    infra: { gpuMemoryGb: 80, gpuClass: 'A100-80G, H100/H200, or 2 x L40S', architecture: 'Vision endpoint + OCR + parse + table-structure + text validation' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'vision', 'ocr', 'text-generation'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.2-90b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-ocr-v1', 'nvidia-nemoretriever-parse', 'nvidia-nemoretriever-table-structure-v1']
  },
  {
    id: 'medical-scribe',
    name: 'Clinical scribe',
    category: 'Healthcare',
    complexity: 'high',
    pattern: 'Unsupported Speech',
    desc: 'Clinical speech and ambient transcription are hidden in strict v2.6 mode because the PDF does not validate the complete ASR path.',
    defaults: { users: 500, concurrency: 0, latency: 'near-real-time', deployment: 'private' },
    models: ['Not supported in strict NAI v2.6'],
    infra: { gpuMemoryGb: 0, gpuClass: 'Hidden in strict mode', architecture: 'Custom validation required outside the strict catalog' },
    strictVisible: false,
    pdfSupportStatus: 'hidden',
    requiredCapabilities: ['speech'],
    allowedValidatedModelIds: [],
    defaultValidatedModelId: ''
  },
  {
    id: 'code-assistant',
    name: 'Developer code assistant',
    category: 'Software',
    complexity: 'high',
    pattern: 'Validated Code RAG',
    desc: 'Enterprise codebase Q&A and coding help using validated code-capable endpoints.',
    defaults: { users: 1000, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Devstral-Small-2507', 'CodeLlama-34B-Instruct-hf'],
    infra: { gpuMemoryGb: 80, gpuClass: 'A100/H100/H200/RTX PRO 6000', architecture: 'Code endpoint + embedqa + rerankqa over repositories' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['code', 'retrieval', 'text-generation'],
    allowedValidatedModelIds: ['hf-devstral-small-2507', 'hf-codellama-34b-instruct'],
    defaultValidatedModelId: 'hf-devstral-small-2507',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'security-triage',
    name: 'SOC alert triage assistant',
    category: 'Security',
    complexity: 'high',
    pattern: 'Validated Security RAG',
    desc: 'Correlates alerts, logs, and playbooks with validated text endpoints and safety controls.',
    defaults: { users: 150, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-70B-Instruct', 'Llama-3.3-70B-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium validated text endpoint + retrieval + guardrails' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'guardrail'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-70b-instruct', 'hf-meta-llama-3.3-70b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2', 'nvidia-llama-3.1-nemoguard-8b-content-safety']
  }
  ,
  {
    id: 'phishing-analysis',
    name: 'Phishing email analysis',
    category: 'Security',
    complexity: 'medium',
    pattern: 'Validated Guardrail Classification',
    desc: 'Classify suspicious emails and extract findings with validated safety-capable endpoints.',
    defaults: { users: 100, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['llama-3.1-nemoguard-8b-content-safety', 'Mistral-7B-Instruct-v0.3'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G, A100-80G, H100/H200', architecture: 'Guardrail endpoint + optional text summarizer' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['guardrail', 'classification', 'text-generation'],
    allowedValidatedModelIds: ['nvidia-llama-3.1-nemoguard-8b-content-safety', 'hf-mistral-7b-instruct-v0.3'],
    defaultValidatedModelId: 'nvidia-llama-3.1-nemoguard-8b-content-safety',
    companionEndpointIds: []
  },
  {
    id: 'knowledge-search',
    name: 'Enterprise knowledge search',
    category: 'RAG',
    complexity: 'medium',
    pattern: 'Validated RAG',
    desc: 'Search and summarize enterprise documents with a validated retrieval stack.',
    defaults: { users: 3000, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + embedqa + rerankqa + vector store' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'reranking'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'hr-policy-bot',
    name: 'HR policy bot',
    category: 'Assistant',
    complexity: 'low',
    pattern: 'Validated RAG',
    desc: 'Answer HR questions from policy documents with a validated small text endpoint.',
    defaults: { users: 1000, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'it-helpdesk',
    name: 'IT helpdesk assistant',
    category: 'Assistant',
    complexity: 'medium',
    pattern: 'Validated RAG + Actions',
    desc: 'Troubleshooting and ticket drafting with validated retrieval and text endpoints.',
    defaults: { users: 2000, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval + workflow hooks' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'field-service-copilot',
    name: 'Field service copilot',
    category: 'Operations',
    complexity: 'medium',
    pattern: 'Validated RAG + Mobile',
    desc: 'Assist technicians with manuals and repair flows using validated small text endpoints.',
    defaults: { users: 800, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval + offline content sync' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'document-classification',
    name: 'Document classification',
    category: 'Documents',
    complexity: 'low',
    pattern: 'Validated Vision Classification',
    desc: 'Categorize enterprise documents with a validated vision classifier or vision-capable endpoint.',
    defaults: { users: 30, concurrency: 0, latency: 'batch', deployment: 'private' },
    models: ['google/vit-base-patch16-224', 'Llama-3.2-11B-Vision-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or A100-80G', architecture: 'Vision classifier endpoint' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['vision', 'classification'],
    allowedValidatedModelIds: ['other-google-vit-base-patch16-224', 'hf-meta-llama-3.2-11b-vision-instruct'],
    defaultValidatedModelId: 'other-google-vit-base-patch16-224',
    companionEndpointIds: []
  },
  {
    id: 'image-captioning',
    name: 'Image captioning',
    category: 'Vision',
    complexity: 'low',
    pattern: 'Validated Vision',
    desc: 'Generate captions for images with validated vision-capable endpoints.',
    defaults: { users: 100, concurrency: 0, latency: 'interactive', deployment: 'cloud' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Llama-3.2-90B-Vision-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G, A100-80G, or RTX PRO 6000-96G', architecture: 'Vision endpoint with strict validated GPU matrix' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['vision'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.2-90b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: []
  },
  {
    id: 'video-search',
    name: 'Video search and summarization',
    category: 'Media',
    complexity: 'high',
    pattern: 'Unsupported Video',
    desc: 'Video and speech indexing are hidden in strict v2.6 mode because the PDF does not validate this as a complete packaged path.',
    defaults: { users: 100, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Not supported in strict NAI v2.6'],
    infra: { gpuMemoryGb: 0, gpuClass: 'Hidden in strict mode', architecture: 'Custom validation required outside the strict catalog' },
    strictVisible: false,
    pdfSupportStatus: 'hidden',
    requiredCapabilities: ['video', 'speech'],
    allowedValidatedModelIds: [],
    defaultValidatedModelId: ''
  },
  {
    id: 'surveillance-analytics',
    name: 'Surveillance analytics',
    category: 'Vision',
    complexity: 'high',
    pattern: 'Unsupported CV',
    desc: 'Edge CV object detection is hidden in strict v2.6 mode because the PDF does not validate this workload as a packaged endpoint path.',
    defaults: { users: 20, concurrency: 0, latency: 'near-real-time', deployment: 'edge' },
    models: ['Not supported in strict NAI v2.6'],
    infra: { gpuMemoryGb: 0, gpuClass: 'Hidden in strict mode', architecture: 'Custom validation required outside the strict catalog' },
    strictVisible: false,
    pdfSupportStatus: 'hidden',
    requiredCapabilities: ['cv'],
    allowedValidatedModelIds: [],
    defaultValidatedModelId: ''
  },
  {
    id: 'quality-inspection',
    name: 'Manufacturing quality inspection',
    category: 'Vision',
    complexity: 'high',
    pattern: 'Unsupported CV',
    desc: 'Production-line CV inference is hidden in strict v2.6 mode because the PDF does not validate this workload as a packaged endpoint path.',
    defaults: { users: 50, concurrency: 0, latency: 'near-real-time', deployment: 'edge' },
    models: ['Not supported in strict NAI v2.6'],
    infra: { gpuMemoryGb: 0, gpuClass: 'Hidden in strict mode', architecture: 'Custom validation required outside the strict catalog' },
    strictVisible: false,
    pdfSupportStatus: 'hidden',
    requiredCapabilities: ['cv'],
    allowedValidatedModelIds: [],
    defaultValidatedModelId: ''
  },
  {
    id: 'predictive-maintenance',
    name: 'Predictive maintenance assistant',
    category: 'Operations',
    complexity: 'medium',
    pattern: 'Validated Assistant',
    desc: 'Explain anomalies and maintenance guidance with a validated small text endpoint.',
    defaults: { users: 150, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + optional retrieval context' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: []
  },
  {
    id: 'etl-enrichment',
    name: 'ETL data enrichment',
    category: 'Data',
    complexity: 'medium',
    pattern: 'Validated Batch Text',
    desc: 'Classify and enrich records during ETL with a validated small text endpoint.',
    defaults: { users: 10, concurrency: 0, latency: 'batch', deployment: 'cloud' },
    models: ['Mistral-7B-Instruct-v0.3', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Batch validated text endpoint' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation'],
    allowedValidatedModelIds: ['hf-mistral-7b-instruct-v0.3', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-7b-instruct-v0.3',
    companionEndpointIds: []
  },
  {
    id: 'sql-analyst',
    name: 'Natural language SQL analyst',
    category: 'Data',
    complexity: 'medium',
    pattern: 'Validated SQL',
    desc: 'Generate SQL and explain results with a validated code-capable endpoint.',
    defaults: { users: 500, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Devstral-Small-2507', 'CodeLlama-34B-Instruct-hf'],
    infra: { gpuMemoryGb: 80, gpuClass: 'A100-80G, H100/H200, or RTX PRO 6000-96G', architecture: 'Validated code endpoint with schema context' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['sql', 'code', 'text-generation'],
    allowedValidatedModelIds: ['hf-devstral-small-2507', 'hf-codellama-34b-instruct'],
    defaultValidatedModelId: 'hf-devstral-small-2507',
    companionEndpointIds: []
  },
  {
    id: 'fraud-investigation',
    name: 'Fraud investigation assistant',
    category: 'FSI',
    complexity: 'high',
    pattern: 'Validated Graph RAG',
    desc: 'Correlate entities, transactions, and cases with a premium validated text endpoint.',
    defaults: { users: 200, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Llama-3.3-70B-Instruct', 'Meta-Llama-3.1-70B-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.3-70b-instruct', 'hf-meta-llama-3.1-70b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.3-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'loan-origination',
    name: 'Loan origination assistant',
    category: 'FSI',
    complexity: 'medium',
    pattern: 'Validated Document AI',
    desc: 'Collect documents and summarize applicant packages with validated vision and document retriever endpoints.',
    defaults: { users: 300, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G, A100-80G, or RTX PRO 6000-96G', architecture: 'Vision or text endpoint + parse/OCR + table-structure' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'vision', 'text-generation'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-parse', 'nvidia-nemoretriever-ocr-v1', 'nvidia-nemoretriever-table-structure-v1']
  }
  ,
  {
    id: 'marketing-content',
    name: 'Marketing content generation',
    category: 'Creative',
    complexity: 'low',
    pattern: 'Validated Text Generation',
    desc: 'Generate campaign drafts with validated text endpoints only.',
    defaults: { users: 400, concurrency: 0, latency: 'interactive', deployment: 'cloud' },
    models: ['Mistral-7B-Instruct-v0.3', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation'],
    allowedValidatedModelIds: ['hf-mistral-7b-instruct-v0.3', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-mistral-7b-instruct-v0.3',
    companionEndpointIds: []
  },
  {
    id: 'translation-service',
    name: 'Enterprise translation service',
    category: 'Language',
    complexity: 'medium',
    pattern: 'Validated Text Translation',
    desc: 'Translate content with validated general text endpoints inside the strict catalog.',
    defaults: { users: 600, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Mistral-7B-Instruct-v0.3', 'gemma-2-9b-it'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint for translation workflow' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation'],
    allowedValidatedModelIds: ['hf-mistral-7b-instruct-v0.3', 'other-google-gemma-2-9b-it'],
    defaultValidatedModelId: 'hf-mistral-7b-instruct-v0.3',
    companionEndpointIds: []
  },
  {
    id: 'legal-discovery',
    name: 'Legal discovery review',
    category: 'Legal',
    complexity: 'high',
    pattern: 'Validated Document RAG',
    desc: 'Assist review teams with large document sets using premium validated text plus document AI companions.',
    defaults: { users: 250, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-70B-Instruct', 'Llama-3.2-11B-Vision-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium text endpoint + parse/OCR + rerankqa' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-70b-instruct', 'hf-meta-llama-3.2-11b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-70b-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-parse', 'nvidia-nemoretriever-ocr-v1', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'research-assistant',
    name: 'Research assistant',
    category: 'Knowledge',
    complexity: 'medium',
    pattern: 'Validated Web + RAG',
    desc: 'Combine web research and private corpus summarization with validated text and retrieval endpoints.',
    defaults: { users: 200, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-70B-Instruct'],
    infra: { gpuMemoryGb: 80, gpuClass: 'RTX PRO 6000-96G or 2 x L40S / 2 x H100-class GPUs', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-70b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'education-tutor',
    name: 'Education tutor',
    category: 'Education',
    complexity: 'medium',
    pattern: 'Validated RAG + Dialogue',
    desc: 'Provide grounded tutoring with validated small text endpoints and retrieval.',
    defaults: { users: 2000, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'compliance-monitor',
    name: 'Compliance monitoring assistant',
    category: 'Governance',
    complexity: 'high',
    pattern: 'Validated Policy + Guardrails',
    desc: 'Map artifacts and activity to policies with premium text endpoints and validated guardrails.',
    defaults: { users: 150, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-70B-Instruct', 'llama-3.1-nemoguard-8b-topic-control'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium text endpoint + guardrail endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'guardrail', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-70b-instruct', 'nvidia-llama-3.1-nemoguard-8b-topic-control', 'hf-meta-llama-guard-3-8b'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.1-nemoguard-8b-topic-control', 'hf-meta-llama-guard-3-8b', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'proposal-generator',
    name: 'Proposal / RFP response assistant',
    category: 'Sales',
    complexity: 'medium',
    pattern: 'Validated RAG + Generation',
    desc: 'Draft proposal responses from approved content with validated text and retrieval endpoints.',
    defaults: { users: 500, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'procurement-bot',
    name: 'Procurement assistant',
    category: 'Operations',
    complexity: 'medium',
    pattern: 'Validated RAG + Workflow',
    desc: 'Supplier comparison, clause checks, and request drafting with validated text and retrieval endpoints.',
    defaults: { users: 150, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'resume-screening',
    name: 'Resume screening assistant',
    category: 'HR',
    complexity: 'medium',
    pattern: 'Validated Document Ranking',
    desc: 'Extract and rank candidate information with validated document AI plus text summarization.',
    defaults: { users: 120, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Vision endpoint + parse/OCR + text summary' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'vision', 'text-generation'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-parse', 'nvidia-nemoretriever-ocr-v1']
  },
  {
    id: 'onboarding-assistant',
    name: 'Employee onboarding assistant',
    category: 'HR',
    complexity: 'low',
    pattern: 'Validated RAG',
    desc: 'Help new hires with onboarding tasks and documentation through a validated small text endpoint.',
    defaults: { users: 300, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'ecommerce-assistant',
    name: 'E-commerce shopping assistant',
    category: 'Retail',
    complexity: 'medium',
    pattern: 'Validated Product RAG',
    desc: 'Support product Q&A and discovery with validated text and retrieval endpoints.',
    defaults: { users: 5000, concurrency: 0, latency: 'interactive', deployment: 'cloud' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + embedqa + rerankqa' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'reranking'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  }
  ,
  {
    id: 'product-recommendation-explainer',
    name: 'Recommendation explainer',
    category: 'Retail',
    complexity: 'low',
    pattern: 'Validated Text Overlay',
    desc: 'Explain recommendation context using a validated small text endpoint.',
    defaults: { users: 2000, concurrency: 0, latency: 'interactive', deployment: 'cloud' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-7B-Instruct-v0.3'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-7b-instruct-v0.3'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: []
  },
  {
    id: 'edge-ocr',
    name: 'Edge OCR and document intake',
    category: 'Documents',
    complexity: 'medium',
    pattern: 'Validated Document AI',
    desc: 'Capture and extract documents at branch or edge locations with validated vision and OCR services.',
    defaults: { users: 300, concurrency: 0, latency: 'near-real-time', deployment: 'edge' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Llama-3.2-90B-Vision-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G, A100-80G, or H200-141G', architecture: 'Vision endpoint + OCR + parse companions' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['document-ai', 'vision', 'ocr'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.2-90b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-ocr-v1', 'nvidia-nemoretriever-parse']
  },
  {
    id: 'graph-rag-investigation',
    name: 'Graph RAG investigation workspace',
    category: 'Knowledge',
    complexity: 'high',
    pattern: 'Validated Graph RAG',
    desc: 'Investigate connected records, people, systems, and events with premium validated text endpoints.',
    defaults: { users: 100, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Llama-3.3-70B-Instruct', 'Meta-Llama-3.1-70B-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.3-70b-instruct', 'hf-meta-llama-3.1-70b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.3-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'agentic-orchestration',
    name: 'Agentic workflow orchestration',
    category: 'Automation',
    complexity: 'high',
    pattern: 'Validated Agentic',
    desc: 'Planner/executor/reviewer loops constrained to validated premium text endpoints.',
    defaults: { users: 100, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-70B-Instruct', 'Llama-3.3-70B-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium text endpoint + retrieval + guardrails' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'guardrail'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-70b-instruct', 'hf-meta-llama-3.3-70b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.1-nemoguard-8b-content-safety', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'batch-summarization',
    name: 'Batch summarization pipeline',
    category: 'Batch',
    complexity: 'low',
    pattern: 'Validated Batch Text',
    desc: 'Summarize large document sets overnight with a validated small text endpoint.',
    defaults: { users: 5, concurrency: 0, latency: 'batch', deployment: 'cloud' },
    models: ['Mistral-7B-Instruct-v0.3', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Batch validated text endpoint' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation'],
    allowedValidatedModelIds: ['hf-mistral-7b-instruct-v0.3', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-7b-instruct-v0.3',
    companionEndpointIds: []
  },
  {
    id: 'multimodal-search',
    name: 'Multimodal enterprise search',
    category: 'Multimodal',
    complexity: 'high',
    pattern: 'Validated Multimodal RAG',
    desc: 'Search text, diagrams, slides, screenshots, and images with validated vision and retrieval endpoints.',
    defaults: { users: 500, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Llama-3.2-11B-Vision-Instruct', 'Llama-3.2-90B-Vision-Instruct'],
    infra: { gpuMemoryGb: 80, gpuClass: 'A100-80G, H100/H200, or 2 x L40S', architecture: 'Vision endpoint + graphic/page parse + embedqa + rerankqa' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['vision', 'document-ai', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.2-11b-vision-instruct', 'hf-meta-llama-3.2-90b-vision-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.2-11b-vision-instruct',
    companionEndpointIds: ['nvidia-nemoretriever-graphic-elements-v1', 'nvidia-nemoretriever-parse', 'nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'customer-360',
    name: 'Customer 360 assistant',
    category: 'Sales',
    complexity: 'medium',
    pattern: 'Validated RAG + CRM',
    desc: 'Unify notes, CRM, support, and product usage with validated text and retrieval endpoints.',
    defaults: { users: 1000, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'supply-chain-risk',
    name: 'Supply chain risk analyst',
    category: 'Operations',
    complexity: 'medium',
    pattern: 'Validated RAG + External Data',
    desc: 'Summarize supplier exposure, delays, and disruptions with validated text and retrieval endpoints.',
    defaults: { users: 120, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'scientific-literature',
    name: 'Scientific literature copilot',
    category: 'Research',
    complexity: 'medium',
    pattern: 'Validated RAG',
    desc: 'Search papers and extract findings with validated text and retrieval endpoints.',
    defaults: { users: 200, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-70B-Instruct'],
    infra: { gpuMemoryGb: 80, gpuClass: 'RTX PRO 6000-96G or H100/H200-class GPUs', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-70b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  },
  {
    id: 'case-management',
    name: 'Case management summarizer',
    category: 'Public Sector',
    complexity: 'medium',
    pattern: 'Validated RAG + Workflow',
    desc: 'Summarize long-running cases with validated text and retrieval endpoints.',
    defaults: { users: 300, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Mistral-Nemo-Instruct-2407', 'Meta-Llama-3.1-8B-Instruct'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-mistral-nemo-instruct-2407', 'hf-meta-llama-3.1-8b-instruct'],
    defaultValidatedModelId: 'hf-mistral-nemo-instruct-2407',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'branch-assistant',
    name: 'Branch or retail associate assistant',
    category: 'Retail',
    complexity: 'low',
    pattern: 'Validated RAG',
    desc: 'Fast answers to SOPs, products, and scripts through a validated small text endpoint.',
    defaults: { users: 2000, concurrency: 0, latency: 'interactive', deployment: 'hybrid' },
    models: ['Meta-Llama-3.1-8B-Instruct', 'Mistral-Nemo-Instruct-2407'],
    infra: { gpuMemoryGb: 48, gpuClass: 'L40S-48G or RTX PRO 6000-96G', architecture: 'Validated text endpoint + retrieval' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-8b-instruct', 'hf-mistral-nemo-instruct-2407'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-8b-instruct',
    companionEndpointIds: ['nvidia-llama-3.2-nv-embedqa-1b-v2']
  },
  {
    id: 'operations-war-room',
    name: 'Operations war-room assistant',
    category: 'Operations',
    complexity: 'high',
    pattern: 'Validated Agentic RAG',
    desc: 'Combine monitoring, tickets, topology, and runbooks with premium validated text endpoints and guardrails.',
    defaults: { users: 80, concurrency: 0, latency: 'interactive', deployment: 'private' },
    models: ['Meta-Llama-3.1-70B-Instruct', 'Llama-3.3-70B-Instruct'],
    infra: { gpuMemoryGb: 160, gpuClass: '2 x A100/H100/H100 NVL/H200 or 4 x L40S', architecture: 'Premium text endpoint + retrieval + guardrails' },
    strictVisible: true,
    pdfSupportStatus: 'validated',
    requiredCapabilities: ['text-generation', 'retrieval', 'guardrail'],
    allowedValidatedModelIds: ['hf-meta-llama-3.1-70b-instruct', 'hf-meta-llama-3.3-70b-instruct'],
    defaultValidatedModelId: 'hf-meta-llama-3.1-70b-instruct',
    companionEndpointIds: ['nvidia-llama-3.1-nemoguard-8b-content-safety', 'nvidia-llama-3.2-nv-rerankqa-1b-v2']
  }
];
